# Generated by Django 5.0.2 on 2024-03-11 02:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aplicacion', '0002_rename_titulos_jugador_altura'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='equipo',
            name='fecha_creacion',
        ),
        migrations.AddField(
            model_name='equipo',
            name='fundacion',
            field=models.IntegerField(default=1980),
        ),
    ]
